### ISSUE TITLE
Python solution of Exercise08 prb with C_block_form.cl part

### ISSUE THREAD

**Issue by RaoulChartreuse** [HandsOnOpenCL/Exercises-Solutions#49]
I add no problem to launch most of the example, but the solution of the exercice9 I get this error message :
===== OpenCL, A and B in block form in local memory, order 1024 ======

Traceback (most recent call last):
  File "matmul.py", line 187, in <module>
    d_a, d_b, d_c, localmem1, localmem2)
  File "/usr/local/lib/python2.7/dist-packages/pyopencl/**init**.py", line 466, in kernel_call
    global_offset, wait_for, g_times_l=g_times_l)
pyopencl.LogicError: clEnqueueNDRangeKernel failed: invalid work group size

**Comment by tomdeakin** [comment]
Closed as looks device specific issue.
