### ISSUE TITLE
Bug in one of matrix multiplication versions

### ISSUE THREAD

**Issue by azatsman** [HandsOnOpenCL/Exercises-Solutions#61]
The fastest version in Exersize08 seems to have a bug: while it passes the existsting unit test it fails a slightly more rigorous one. There are two changes needed to reproduce the problem, both in the host code:

1. Initialize input matrices to non-constant, but preferably small, values. I used this code:
<pre>
          void initmat(int N, std::vector<float>& A, std::vector<float>& B, std::vector<float>& C)
          {
            int i, j, vv = 1;
            for (i = 0; i < N; i++)
              for (j = 0; j < N; j++)
                A[i*N+j] = static_cast<float>((vv++) % 17);
            for (i = 0; i < N; i++)
              for (j = 0; j < N; j++)
                B[i*N+j] = static_cast<float>((vv++) % 11);
            for (i = 0; i < N; i++)
              for (j = 0; j < N; j++)
                C[i*N+j] = static_cast<float>((vv++) % 19);
          }
    </pre>

 2.  Compute the output matrix on the host and use it later to verify the OpenCL versions.

On my machine all OpenCL versions passed with the exception of the <code>C_block_form.cl</code> kernel:

<pre>
Using OpenCL device: GeForce GTX 1080

===== Sequential, matrix mult (dot prod), order 1024 on host CPU ======
 1.99 seconds at 1079.7 MFLOPS 

===== OpenCL, matrix mult, C(i,j) per work item, order 1024 ======
 0.05 seconds at 43826.2 MFLOPS 

===== OpenCL, matrix mult, C row per work item, order 1024 ======
 0.17 seconds at 12341.9 MFLOPS 

===== OpenCL, matrix mult, C row, A row in priv mem, order 1024 ======
 0.08 seconds at 26512.1 MFLOPS 

===== OpenCL, mat mult, C row, priv A, B cols loc, order 1024 ======
 0.07 seconds at 30246.2 MFLOPS 

===== Parallel matrix mult (blocked), order 1024 on device ======
 0.00 seconds at 1073741.9 MFLOPS 

Errors in multiplication: 31091400704.000000
</pre>

**Comment by tomdeakin** [comment]
Thanks for spotting this. There was a bug in the calculation of the block offsets.
