### ISSUE TITLE
How to dynamically size private array length to prevent hard-coding as in C_row_priv.cl? 

### ISSUE THREAD

**Issue by cirosantilli** [HandsOnOpenCL/Exercises-Solutions#63]
https://github.com/HandsOnOpenCL/Exercises-Solutions/blob/a908ac3f0fadede29f2735eb1264b0db7f4311a0/Solutions/Exercise08/C_row_priv.cl#L10 hardcodes 1024 private array size:

```
float Awrk[1024];
```

Can we avoid hardcoding that `1024` there?

Searched for VLAs, but not in the language: http://stackoverflow.com/questions/17995991/variable-length-array-declaration-not-allowed-in-opencl-why

We can of course patch the cl kernel code string, but that is ugly.

**Comment by tomdeakin** [comment]
You can use the `char * options` argument of `clBuildProgram` to pass in compiler defines such as `-DPRIV=1024`. Inside the kernel you can then:
```
#ifndef PRIV
#define PRIV 1024
#endif

float Awrk[PRIV];
```

**Comment by cirosantilli** [comment]
Awesome! Shouldn't we do that in the code I mentioned as well?
