### ISSUE TITLE
Exercise 2 compiles with OpenMP but it doesn't use it

### ISSUE THREAD

**Issue by BourbonCreams** [HandsOnOpenCL/Exercises-Solutions#68]
Hi there, as the title states I managed to run Exercise 2 removing "-fopenmp" from line 8 (LIBS = ...). I don't think the code uses OpenMP so why does it appear on the Makefile? I didn't have OpenMP so I couldn't run it, that's how I ended up trying it without OpenMP.

**Comment by tomdeakin** [comment]
Good spot. Thanks for the fix in #69.
